version = 1

test_patterns = ["*_test.go"]

exclude_patterns = ["/examples"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/32Bites/wetgear"]

[[transformers]]
name = "gofmt"
enabled = true
